1) Импортирование библиотеки

In [ ]:
import numpy as np

2)Примеры создания массивов


Одномерный массив

In [11]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

Двумерный массив(матрица)

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

Двумерный массив из нулей

In [14]:
z_a=np.zeros((5,3))
z_a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Матрица единиц

In [15]:
o_a=np.ones((2,3))
o_a

array([[1., 1., 1.],
       [1., 1., 1.]])

Единичная матрица

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Создание массива, но без заполнения(заполнен мусором из памяти)

In [20]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Массив от 0 до 10 с шагом 2

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

3)Демонстрация атрибутов

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


Форма

In [23]:
a.shape

(5,)

Тип данных массива

In [7]:
type(a)

numpy.ndarray

4)Примеры индексирования и срезов

Элемент с индексом 2

In [24]:
a[2]

np.int64(3)

Последний элемент

In [25]:
a[-1]

np.int64(5)

Элемент [0,2], строка 0 столбец 2(индексы начинаются с 0)

In [28]:
b[0,2]

np.int64(3)

Срез массива с 1 индекса по 3(не включительно)

In [29]:
a[1:3]

array([2, 3])

Срез массива каждый второй элемент

In [30]:
a[::2]

array([1, 3, 5])

Срез матрицы, все строки, первые два столбца

In [32]:
b[:,:2]

array([[1, 2],
       [4, 5]])

5)Примеры веркторных операций и базовых статистик

In [34]:
aa = np.array([1, 2, 3, 4, 5])
ab = np.array([10, 20, 30, 40, 50])

Поэлементное сложение

In [35]:
aa+ab

array([11, 22, 33, 44, 55])

Поэлементное умножение

In [36]:
aa*ab

array([ 10,  40,  90, 160, 250])

Умножение на скаляр

In [37]:
aa*2

array([ 2,  4,  6,  8, 10])

Базовые операции статистики

Среднее значение

In [38]:
np.mean(aa)

np.float64(3.0)

Сумма всех элементов

In [39]:
np.sum(aa)

np.int64(15)

Минимальное, максимальное значение

In [41]:
np.min(aa)


np.int64(1)

In [42]:
np.max(aa)

np.int64(5)

Стандартное отклонение

In [43]:
np.std(aa)

np.float64(1.4142135623730951)

Среднее по элемантам матрицы

In [44]:
np.mean(b)

np.float64(3.5)

Сумма по столбцам

In [45]:
np.sum(b,axis=0)

array([5, 7, 9])

Среднее по строкам

In [46]:
np.mean(b,axis=1)

array([2., 5.])